baseURL = "/"
title = "Thrive In Vitality"
author = "username"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true



# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog']

  [params.logo]
    main = "./img/logo/logo.png"
    alt = "TIV Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Thrive In Vitality"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fa5 = true

  [params.homepage_meta_tags]
    meta_description = "A Holistic approach to your health needs"
    meta_og_title = "Thrive in Vitality"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://github.com/ThriveInVitality/Business-Page/blob/main/static/img/logo/logo.png"
    meta_og_description = "A Holistic approach to your health needs"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  [[menu.main]]
    identifier = "thankyou"
    # name = "Thank You"
    url = "/thankyou/"
    weight = 6
  
  [[menu.main]]
    identifier = "about-coach"
    # name = "Meet Amy"
    url = "/health-coach/"
    weight = 7
  

  # Footer Menu
  [[menu.footer]]
    name = "Homepage"
    url = "/"
      weight = 1

  # [[menu.footer]]
  #   name = "Github"
  #   url = "https://github.com/opera7133/tella"
  #   pre = "<i class='icon-github text-2xl'></i>"
  #     weight = 2
